apiVersion: v1
kind: Service
metadata:
  name: positions-service
spec:
  selector:
    app: positions-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
